version: '3'

services:
  go:
    image: golang:1.15.5-alpine
    working_dir: /s3ls
    entrypoint: go
    environment:
      CGO_ENABLED: '0'
    volumes:
      - .:/s3ls
      - go:/go

volumes:
  go:
